language: cpp

os: linux
dist: trusty
sudo: false

notifications:
        email: false

matrix:
        include:
                ##########################################################################
                # Clang on OSX
                ##########################################################################
                - os: osx
                  osx_image: xcode8.3
                  compiler: clang
                  env: BUILD_TYPE=Release

                - os: osx
                  osx_image: xcode8.3
                  compiler: clang
                  env: BUILD_TYPE=Debug

                - os: osx
                  osx_image: xcode8.3
                  compiler: clang
                  env: BUILD_TYPE=ASan

                ##########################################################################
                # Clang on Linux
                ##########################################################################
                - compiler: clang
                  env: BUILD_TYPE=Release
                  addons: &valgrind
                        apt:
                                sources:
                                        - ubuntu-toolchain-r-test
                                packages:
                                        - valgrind

                - compiler: clang
                  env: BUILD_TYPE=Debug
                  addons: *valgrind

                - compiler: clang
                  env: BUILD_TYPE=ASan
                  addons: *valgrind

                ##########################################################################
                # GCC on Linux 
                ##########################################################################

                - compiler: gcc
                  env: BUILD_TYPE=Release
                  addons: *valgrind

                - compiler: gcc
                  env: BUILD_TYPE=Debug
                  addons: *valgrind

                - compiler: gcc
                  env: BUILD_TYPE=ASan
                  addons: *valgrind

before_script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
        - make -j2
        - ctest -V
        - |
          if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
                ctest -T memcheck
          fi
