language: cpp

os:
        - linux
        - osx

compiler:
        - gcc
        - clang

env:
        matrix:
                - BUILD_TYPE="Release"
                - BUILD_TYPE="Debug"
                - BUILD_TYPE="ASan"
                - BUILD_TYPE="MemSan"

matrix:
        exclude:
                - os: osx
                  compiler: gcc
                - os: osx
                  env: BUILD_TYPE="Debug"
                - os: linux
                  compiler: gcc
                  env: BUILD_TYPE="MemSan"

before_script:
        - cd ${TRAVIS_BUILD_DIR}
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
        - make -j 2
        - make -V -j 2
